# Generated by Django 5.2.3 on 2025-06-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Planning', max_length=50),
        ),
    ]
