# Generated by Django 5.2.2 on 2025-06-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular'), ('pomodoro', 'Pomodoro')], default='regular', max_length=10),
        ),
    ]
